spring.application.name=careercompass

spring.datasource.url=jdbc:mysql://localhost:3306/career_compass
spring.datasource.username=root
spring.datasource.password=Pavan@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081